version: '3.9'

services:

  app:
    image: tp-nosql:latest
    build:
      context: .
      args:
        NODE_ENV: production
    container_name: app
    restart: always
    networks:
      - tp-nosql
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      POSTGRES_URI: "postgresql://postgres:password@postgres:5432/tp-nosql?schema=public"
      NEO4J_URI: "bolt://neo4j:password@neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "password"
    depends_on:
      - neo4j
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
#    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - tp-nosql
    ports:
      - 5432:5432
    volumes:
      - tp-nosql-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  neo4j:
    image: neo4j:community
    container_name: neo4j
    restart: always
    networks:
      - tp-nosql
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - tp-nosql-neo4j:/data
    environment:
      NEO4J_AUTH: neo4j/password

networks:
  tp-nosql:
    driver: bridge

volumes:
  tp-nosql-neo4j:
    driver: local
  tp-nosql-postgres:
    driver: local
